// WARNING: DO NOT EDIT.  This file is automatically generated
// Written by aws-amplify-serverless-plugin/1.4.1 on 2019-04-02T08:37:02.526Z

const awsmobile = {
  aws_cloud_logic_custom: [
    {
      endpoint: 'https://c60esxid12.execute-api.us-east-1.amazonaws.com/dev',
      name: 'ApiGatewayRestApi',
      region: 'us-east-1'
    }
  ],
  aws_cognito_region: 'us-east-1',
  aws_project_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_75UGv7Hjf',
  aws_user_pools_web_client_id: '7jvdn6qsmca4hdnc5jf638iakl'
}

export default awsmobile
