// WARNING: DO NOT EDIT.  This file is automatically generated
// Written by aws-amplify-serverless-plugin/1.4.1 on 2019-03-15T21:50:10.395Z

const awsmobile = {
  aws_cloud_logic_custom: [
    {
      endpoint: 'https://kwkkg3ml2j.execute-api.us-east-1.amazonaws.com/dev',
      name: 'ApiGatewayRestApi',
      region: 'us-east-1'
    }
  ],
  aws_cognito_region: 'us-east-1',
  aws_project_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_1shJPiBk5',
  aws_user_pools_web_client_id: '84ihq907sv2kvniiq4djihgia'
}

export default awsmobile
