// WARNING: DO NOT EDIT.  This file is automatically generated
// Written by aws-amplify-serverless-plugin/1.4.1 on 2019-04-05T14:04:47.414Z

const awsmobile = {
  aws_cloud_logic_custom: [
    {
      endpoint: process.env.AWS_AUTHORIZER,
      name: 'ApiGatewayRestApi',
      region: 'us-east-1'
    }
  ],
  aws_cognito_region: 'us-east-1',
  aws_project_region: 'us-east-1',
  aws_user_pools_id: process.env.AWS_USER_POOL_ID,
  aws_user_pools_web_client_id: process.env.AWS_USER_POOL_WEB_CLIENT_ID
}

export default awsmobile
